#!/bin/bash
# HitWatch4Lox postroot.sh
# Wird mit Root-Rechten nach der Installation aufgerufen

PLUGIN="hitwatch4lox"

# LBHOMEDIR ermitteln - mehrere Methoden als Fallback
if [ -z "$LBHOMEDIR" ]; then
    LBHOMEDIR=$(grep "^LBHOMEDIR=" /etc/environment 2>/dev/null | head -1 | cut -d= -f2 | tr -d '"' | tr -d "'")
fi
if [ -z "$LBHOMEDIR" ]; then
    set -a; source /etc/environment 2>/dev/null; set +a
fi
if [ -z "$LBHOMEDIR" ]; then
    LBHOMEDIR="/opt/loxber""ry"
fi

echo "<INFO> LBHOMEDIR=${LBHOMEDIR}"
echo "<INFO> PLUGIN=${PLUGIN}"

DAEMON="${LBHOMEDIR}/system/daemons/plugins/${PLUGIN}"
HELPER="${LBHOMEDIR}/bin/plugins/${PLUGIN}/netbird_watchdog_helper.sh"
SUDOERS="/etc/sudoers.d/${PLUGIN}"
LOGDIR="${LBHOMEDIR}/log/plugins/${PLUGIN}"

mkdir -p "${LOGDIR}"
chown loxberry:loxberry "${LOGDIR}" 2>/dev/null

# Sudoers-Datei erstellen: NUR die exakten Aufrufe, die der loxberry-User braucht.
# Netbird-Status/-Neustart/-Reboot laufen ausschließlich über netbird_watchdog_helper.sh
# mit festen Unterbefehlen (kein "ALL", kein Passthrough beliebiger Argumente).
# Ausnahme mit Argument: "restart_service *" (Funktion 4, Mosquitto) – der Helper validiert
# den übergebenen Dienstnamen selbst streng, siehe Kommentar dort.
echo "<INFO> Erstelle sudoers: ${SUDOERS}"
{
    echo "# HitWatch4Lox - generated by postroot.sh"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s start\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s stop\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s restart\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s status\n' "${DAEMON}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s check\n' "${HELPER}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s restart\n' "${HELPER}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s reboot\n' "${HELPER}"
    printf 'loxberry ALL=(ALL) NOPASSWD: %s restart_service *\n' "${HELPER}"
} > "${SUDOERS}"

chmod 0440 "${SUDOERS}"
chown root:root "${SUDOERS}"

echo "<INFO> Sudoers Inhalt:"
cat "${SUDOERS}"

if visudo -c -f "${SUDOERS}" >/dev/null 2>&1; then
    echo "<OK> sudoers Syntax OK"
else
    echo "<ERR> sudoers Syntax-Fehler! Entferne Datei."
    cat "${SUDOERS}" >&2
    rm -f "${SUDOERS}"
    exit 1
fi

# Config-Handling: Upgrade-Backup wiederherstellen ODER Default anlegen
# Backup liegt in /tmp/ weil LoxBerry den config/-Ordner beim Update komplett löscht.
CFGDIR="${LBHOMEDIR}/config/plugins/${PLUGIN}"
CFGFILE="${CFGDIR}/${PLUGIN}.cfg"
CFGDEF="${CFGDIR}/${PLUGIN}.cfg.default"
CFGBAK_TMP="/tmp/${PLUGIN}_cfg_upgrade.bak"

mkdir -p "${CFGDIR}"

if [ -f "${CFGBAK_TMP}" ]; then
    cp "${CFGBAK_TMP}" "${CFGFILE}"
    chown loxberry:loxberry "${CFGFILE}" 2>/dev/null
    rm -f "${CFGBAK_TMP}"
    echo "<OK> Konfiguration aus /tmp Backup wiederhergestellt: ${CFGFILE}"
elif [ -f "${CFGDEF}" ] && [ ! -f "${CFGFILE}" ]; then
    cp "${CFGDEF}" "${CFGFILE}"
    chown loxberry:loxberry "${CFGFILE}" 2>/dev/null
    echo "<OK> Standard-Config angelegt (Erstinstallation): ${CFGFILE}"
else
    echo "<INFO> Bestehende Config bleibt erhalten: ${CFGFILE}"
fi

# Daemon-Script und Helper ausführbar machen (LoxBerry kopiert daemon/daemon nach system/daemons/plugins/)
if [ -f "${DAEMON}" ]; then
    chmod +x "${DAEMON}"
    echo "<OK> Daemon-Script chmod +x: ${DAEMON}"
else
    echo "<WARNING> Daemon-Script nicht gefunden: ${DAEMON}"
fi
if [ -f "${HELPER}" ]; then
    chmod +x "${HELPER}"
    echo "<OK> Root-Helper chmod +x: ${HELPER}"
else
    echo "<WARNING> Root-Helper nicht gefunden: ${HELPER}"
fi
PYDAEMON="${LBHOMEDIR}/bin/plugins/${PLUGIN}/hitwatch4lox_daemon.py"
if [ -f "${PYDAEMON}" ]; then
    chmod +x "${PYDAEMON}"
    echo "<OK> Python-Daemon chmod +x: ${PYDAEMON}"
fi

# Daemon nach Installation/Update starten. Anders als bei standortbasierten Plugins
# braucht HitWatch4Lox keine Konfiguration um sinnvoll zu starten (Funktion 1 ist per
# Default aktiv) – daher immer starten, sofern das Daemon-Script vorhanden ist.
DATADIR="${LBHOMEDIR}/data/plugins/${PLUGIN}"
STATEFILE="${DATADIR}/state.json"
ENABLEFILE="${DATADIR}/daemon.enabled"
mkdir -p "${DATADIR}"; chown loxberry:loxberry "${DATADIR}" 2>/dev/null || true

if [ -f "${DAEMON}" ]; then
    echo "<INFO> Starte Daemon..."
    if command -v runuser >/dev/null 2>&1; then
        runuser -u loxberry -- "${DAEMON}" restart >/dev/null 2>&1 \
            && echo "<OK> Daemon als loxberry-User gestartet" \
            || echo "<WARNING> Daemon-Start fehlgeschlagen – bitte manuell starten"
    elif su -s /bin/bash loxberry -c "\"${DAEMON}\" restart >/dev/null 2>&1" 2>/dev/null; then
        echo "<OK> Daemon als loxberry-User gestartet (su)"
    else
        echo "<WARNING> Daemon-Start fehlgeschlagen – kein runuser/su verfügbar. Bitte manuell als loxberry-User starten."
    fi
fi

# /etc/cron.d/ Eintrag: zuverlässiger als user-crontab, überlebt Updates.
# ALLE Jobs prüfen zuerst den Enable-Marker (${ENABLEFILE}) → ein per UI gestopptes
# Plugin wird NICHT ungefragt wieder gestartet.
# @reboot:  startet Daemon 90s nach Systemstart
# 0 3:      täglicher Neustart um 03:00 Uhr (Log-Rotation, frischer Prozess)
# 1-59/5:   Liveness-Watchdog – Prozess tot (pgrep) → Neustart
# 3-59/5:   Hänge-Watchdog – Prozess lebt, aber state.json seit > 20 Min nicht aktualisiert → restart
CROND="/etc/cron.d/${PLUGIN}"
PIDFILE="${LBHOMEDIR}/log/plugins/${PLUGIN}/daemon.pid"
if [ -f "${DAEMON}" ]; then
    cat > "${CROND}" << CRONEOF
# HitWatch4Lox – Autostart + Watchdog + täglicher Restart
# Generiert von postroot.sh – nicht manuell bearbeiten
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

@reboot root sleep 90; if [ -f "${ENABLEFILE}" ]; then runuser -u loxberry -- ${DAEMON} start >/dev/null 2>&1; fi
0 3 * * * root if [ -f "${ENABLEFILE}" ]; then runuser -u loxberry -- ${DAEMON} restart >/dev/null 2>&1; fi
1-59/5 * * * * root if [ -f "${ENABLEFILE}" ] && ! pgrep -f "hitwatch4lox_daemon.py" >/dev/null 2>&1; then sleep 15; if ! pgrep -f "hitwatch4lox_daemon.py" >/dev/null 2>&1; then rm -f "${PIDFILE}"; runuser -u loxberry -- ${DAEMON} start >/dev/null 2>&1; fi; fi
3-59/5 * * * * root if [ -f "${ENABLEFILE}" ] && pgrep -f "hitwatch4lox_daemon.py" >/dev/null 2>&1 && [ -n "\$(find "${STATEFILE}" -mmin +20 2>/dev/null)" ]; then runuser -u loxberry -- ${DAEMON} restart >/dev/null 2>&1; fi
CRONEOF
    chmod 0644 "${CROND}"
    chown root:root "${CROND}" 2>/dev/null
    echo "<OK> Cron-Jobs angelegt: ${CROND}"
    echo "<OK>   @reboot   – Autostart 90s nach Systemstart (nur wenn aktiviert)"
    echo "<OK>   03:00     – Täglicher Restart (nur wenn aktiviert)"
    echo "<OK>   */5 min   – Liveness-Watchdog: Neustart bei totem Prozess"
    echo "<OK>   */5 min   – Hänge-Watchdog: Neustart wenn state.json > 20 Min alt"
else
    echo "<WARNING> Daemon-Script nicht gefunden – Cron konnte nicht angelegt werden: ${DAEMON}"
fi

echo "<OK> postroot.sh abgeschlossen"
exit 0
